allowBuilds:
  esbuild: true
  exifreader: true
  sharp: true

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@yeger/*'
  - 'vue-marmoset-viewer'
  # Renovate security update: mermaid@11.15.0
  - mermaid@11.15.0

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 2880
