minimumReleaseAge: 2880
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@5.7.2 || 6.3.1
  - vite@6.4.1

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - exifreader
  - sharp
  - unrs-resolver
