// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    AwardEntry: typeof import('./components/award/AwardEntry.vue')['default']
    Awards: typeof import('./components/award/Awards.vue')['default']
    Date: typeof import('./components/date/Date.vue')['default']
    DateRange: typeof import('./components/date/DateRange.vue')['default']
    Dot: typeof import('./components/Dot.vue')['default']
    Education: typeof import('./components/education/Education.vue')['default']
    EducationEntry: typeof import('./components/education/EducationEntry.vue')['default']
    Experience: typeof import('./components/experience/Experience.vue')['default']
    ExperienceEntry: typeof import('./components/experience/ExperienceEntry.vue')['default']
    Facts: typeof import('./components/Facts.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FrameworksAndLibraries: typeof import('./components/icons/FrameworksAndLibraries.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconList: typeof import('./components/icons/IconList.vue')['default']
    Languages: typeof import('./components/icons/Languages.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Project: typeof import('./components/project/Project.vue')['default']
    Projects: typeof import('./components/project/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolsAndDatabases: typeof import('./components/icons/ToolsAndDatabases.vue')['default']
  }
}

export {}
