// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Accounts: typeof import('./components/Accounts.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    CarbonBack: typeof import('~icons/carbon/back')['default']
    CarbonBlog: typeof import('~icons/carbon/blog')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonUndo: typeof import('~icons/carbon/undo')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Facts: typeof import('./components/Facts.vue')['default']
    Languages: typeof import('./components/Languages.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    README: typeof import('./components/README.md')['default']
    Software: typeof import('./components/Software.vue')['default']
  }
}

export { }
