name: CD

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Build
        run: yarn build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: static-site-artifact
          path: ./dist
          if-no-files-found: error
  upload-assets:
    name: Upload Assets
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: static-site-artifact
          path: ./dist
      - name: Zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./jan-mueller.zip ./dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: jan-mueller.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: static-site-artifact
          path: ./dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: ./dist
          clean: true
          git-config-name: Jan Müller
          git-config-email: janmueller3698@gmail.com
