name: CI

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version-file: .node-version
      - name: Build, check, and lint
        run: pnpm run ci
      - name: Install cypress
        run: pnpm dlx cypress install
      - name: Test
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: pnpm preview
          browser: chrome
          record: false
          config: video=true
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
      - name: Release
        uses: cycjimmy/semantic-release-action@v4.2.1
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
