name: CI

on: [pull_request, push]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 16
      - name: Build
        run: pnpm turbo build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 16
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Test
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: pnpm preview
          browser: chrome
          record: false
          config: videoUploadOnPasses=false,video=true
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
      - name: Upload Videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
  check:
    name: Check
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 16
      - name: Check Astro
        run: pnpm check:astro
      - name: Check TypeScript
        run: pnpm check:tsc
      - name: Check Vue
        run: pnpm check:vue
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 16
      - name: Lint
        run: pnpm turbo lint
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, check, e2e, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
      - name: Release
        uses: cycjimmy/semantic-release-action@v3.1.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
