name: CI

on: [pull_request, push]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Build
        run: yarn build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - browser: chrome
            record: true
            video: true
          - browser: firefox
            record: true
            video: false
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Test
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: yarn preview
          browser: ${{ matrix.browser }}
          record: ${{ matrix.record }}
          tag: ${{ matrix.browser }},${{ github.event_name }}
          config: videoUploadOnPasses=false,video=${{ matrix.video }}
        env:
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
      - name: Upload Videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Test
        run: yarn test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, e2e, lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
      - name: Release
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
