name: CI

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version-file: .node-version
      - name: Build, check, lint, and test
        run: pnpm run ci
