name: Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete assets of old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
