name: Maintenance

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *'

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been marked stale because there was no activity for 21 days. Without further action, it will be closed in 3 days.'
          days-before-stale: 21
          days-before-close: 3
          exempt-assignees: DerYeger
          exempt-issue-labels: bug, dependencies, enhancement, renovate
          exempt-pr-labels: bug, dependencies, enhancement, renovate
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [javascript]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql.yml
          queries: +security-and-quality
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{ matrix.language }}'
